"""empty message

Revision ID: 250846242bd4
Revises: 
Create Date: 2023-06-02 18:51:26.517099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250846242bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.Date(), nullable=False),
    sa.Column('endTime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('startTime', sa.Date(), nullable=False),
    sa.Column('endTime', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('playertype', sa.String(), nullable=False),
    sa.Column('tournament', sa.Integer(), nullable=True),
    sa.Column('tournamentWinner', sa.Integer(), nullable=True),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('matchWinner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match'], ['match.id'], ),
    sa.ForeignKeyConstraint(['matchWinner'], ['match.id'], ),
    sa.ForeignKeyConstraint(['tournament'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['tournamentWinner'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboard')
    op.drop_table('players')
    op.drop_table('tournament')
    op.drop_table('match')
    # ### end Alembic commands ###
