"""empty message

Revision ID: 9bd523b2e018
Revises: 250846242bd4
Create Date: 2023-06-03 15:56:53.954684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd523b2e018'
down_revision = '250846242bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_matches',
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matches'], ['match.id'], ),
    sa.ForeignKeyConstraint(['players'], ['players.id'], ),
    sa.PrimaryKeyConstraint('players', 'matches')
    )
    op.create_table('win_matches',
    sa.Column('winners', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matches'], ['match.id'], ),
    sa.ForeignKeyConstraint(['winners'], ['players.id'], ),
    sa.PrimaryKeyConstraint('winners', 'matches')
    )
    op.drop_constraint('players_match_fkey', 'players', type_='foreignkey')
    op.drop_constraint('players_matchWinner_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'match')
    op.drop_column('players', 'matchWinner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('matchWinner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('match', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('players_matchWinner_fkey', 'players', 'match', ['matchWinner'], ['id'])
    op.create_foreign_key('players_match_fkey', 'players', 'match', ['match'], ['id'])
    op.drop_table('win_matches')
    op.drop_table('player_matches')
    # ### end Alembic commands ###
