FROM python:3.10-slim-buster


RUN pip install fastapi

RUN pip install uvicorn

RUN pip install requests

RUN pip install docker

RUN pip install fastapi_utils

RUN pip install python-multipart

WORKDIR /app

COPY . .

